const API='/api/fuel-nearby';
let map,userMarker,stationLayer,userPos,radius=10;
const statusEl=document.getElementById('status'),stationsEl=document.getElementById('stations'),countEl=document.getElementById('count');
map=L.map('fuelMap',{zoomControl:true}).setView([42.5,12.5],6);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);
stationLayer=L.layerGroup().addTo(map);
function money(v){return v==null?'—':'€ '+Number(v).toFixed(3).replace('.',',')}
function nav(lat,lon){return 'https://www.google.com/maps/dir/?api=1&destination='+lat+','+lon}
function icon(s){return L.divIcon({className:'fuel-marker',html:'<div style="background:#075c3b;color:#fff;border:3px solid #fff;box-shadow:0 2px 8px #555;border-radius:50%;width:42px;height:42px;display:flex;align-items:center;justify-content:center;font-weight:900">⛽</div>',iconSize:[42,42],iconAnchor:[21,21]})}
function popup(s){return '<div style="min-width:220px"><b style="font-size:16px">'+(s.brand||s.name||'Distributore')+'</b><br><small>'+[s.address,s.municipality].filter(Boolean).join(' · ')+'</small><div style="margin:10px 0;display:grid;gap:5px"><div>🟢 Benzina <b>'+money(s.benzina)+'</b></div><div>🟡 Gasolio <b>'+money(s.gasolio)+'</b></div><div>🔵 GPL <b>'+money(s.gpl)+'</b></div></div><a href="'+nav(s.lat,s.lon)+'" target="_blank" style="display:block;text-align:center;background:#075c3b;color:#fff;padding:9px;border-radius:8px;text-decoration:none;font-weight:800">🧭 NAVIGA</a></div>'}
async function load(){if(!userPos)return;statusEl.textContent='⛽ Cerco i distributori e i prezzi aggiornati...';stationLayer.clearLayers();stationsEl.innerHTML='';
try{const u=API+'?lat='+userPos.lat+'&lon='+userPos.lng+'&radius='+radius+'&limit=150';const r=await fetch(u);const d=await r.json();if(!r.ok)throw new Error(d.error||'Errore API');const list=d.stations||[];countEl.textContent=list.length;statusEl.textContent='✓ '+list.length+' distributori nel raggio di '+radius+' km';list.forEach(s=>{L.marker([s.lat,s.lon],{icon:icon(s)}).addTo(stationLayer).bindPopup(popup(s));const card=document.createElement('article');card.className='station-card';card.innerHTML='<div><h3>'+((s.brand||s.name||'Distributore'))+'</h3><p>'+[s.address,s.municipality].filter(Boolean).join(' · ')+' · 📍 '+Number(s.distance_km).toFixed(1).replace('.',',')+' km</p><div class="prices"><span class="price">🟢 Benzina '+money(s.benzina)+'</span><span class="price">🟡 Gasolio '+money(s.gasolio)+'</span><span class="price">🔵 GPL '+money(s.gpl)+'</span></div></div><a class="nav-btn" target="_blank" href="'+nav(s.lat,s.lon)+'">NAVIGA →</a>';card.onclick=e=>{if(e.target.tagName!=='A')map.setView([s.lat,s.lon],16)};stationsEl.appendChild(card)});if(list.length){const bounds=L.latLngBounds(list.map(s=>[s.lat,s.lon]));bounds.extend([userPos.lat,userPos.lng]);map.fitBounds(bounds,{padding:[45,45],maxZoom:14})}}catch(e){statusEl.textContent='⚠️ '+e.message}}
function goToMyPosition(){if(userPos){map.flyTo(userPos,15,{animate:true,duration:.7});userMarker?.openPopup()}else locate()}
function locate(){statusEl.textContent='📍 Sto localizzando la tua posizione...';navigator.geolocation.getCurrentPosition(p=>{userPos=L.latLng(p.coords.latitude,p.coords.longitude);if(userMarker)map.removeLayer(userMarker);userMarker=L.circleMarker(userPos,{radius:11,color:'#fff',weight:4,fillColor:'#2474d6',fillOpacity:1}).addTo(map).bindPopup('📍 Tu sei qui');goToMyPosition();load()},e=>{statusEl.textContent='⚠️ Non riesco ad accedere alla posizione. Controlla i permessi del browser.'},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}
document.getElementById('locateBtn').onclick=locate;
document.getElementById('recenter').onclick=goToMyPosition;
document.querySelectorAll('[data-radius]').forEach(b=>b.onclick=()=>{radius=Number(b.dataset.radius);document.querySelectorAll('[data-radius]').forEach(x=>x.classList.toggle('active',x===b));load()});