/* L'ULTIMA LETTERA — Static Text Adventure Engine */
(function(){'use strict';
const KEY='UL_STATIC_MASTER_V2';const clone=o=>JSON.parse(JSON.stringify(o));
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
const initial={clues:[],visited:[],history:[],players:['Luca','Sara'],turn:0,finished:false};
const C={
opening:`Il fascicolo UL-01 è aperto. Sono le 22:17 di una sera di ottobre 2026, a Londra.\n\nThomas Vale, consulente finanziario di 58 anni, è stato trovato morto nel suo appartamento di Bloomsbury. La porta non mostra segni di effrazione. Sul tavolo c'è una busta color avorio, senza mittente.\n\nVoi siete gli investigatori. Non c'è un percorso obbligatorio: potete esaminare, interrogare, confrontare e tornare su qualsiasi pista.\n\nScrivete liberamente cosa fate.`,
clues:{
scene:`La scena è ordinata. Sul tavolo: busta color avorio, una tazza da tè vuota e un cucchiaino. Sulla scrivania: taccuino, computer spento e ricevute. Non ci sono segni evidenti di effrazione.`,
letter:`La lettera contiene: “Alcune promesse sopravvivono a chi le ha fatte.” In fondo compare la data 14/10/1984. La carta è moderna, ma la data è chiaramente intenzionale.`,
tea:`La tazza presenta tracce di una sostanza amara. Il laboratorio segnala che non è possibile stabilire la sostanza dal solo esame visivo; il referto completo è nel fascicolo.`,
receipt:`La ricevuta è di un deposito bagagli a King's Cross, ore 18:32, il giorno della morte. Nel cestino c'è un frammento con la sigla “BUD...84”.`,
phone:`Alle 21:41 Thomas ha ricevuto: “Non puoi continuare a nasconderlo.” Alle 21:53 c'è una chiamata persa da un numero non salvato. Il contatto del messaggio è “M.”`,
book:`Nel volume su Budapest una fotografia è segnata. Sul retro: “Hotel Gellért — 14/10/1984”. Un archivio identifica una conferenza privata di giovani economisti britannici tenuta quella sera.`,
notebook:`Nel taccuino: M.V., E.H., R.K. Accanto a M.V. ed E.H. c'è un segno di spunta; accanto a R.K. una domanda. In una pagina successiva: “promessa / copia / originale”.`,
margaret:`Margaret Vale ammette di aver visto Thomas alle 20:10 e di essere andata via alle 20:35. Dice che stavano discutendo di una vecchia questione familiare. Non conosce, a suo dire, il significato della lettera.`,
edward:`Edward Hart sostiene di essere rimasto in ufficio fino alle 21:30. Conosceva Thomas da vent'anni e nega di sapere qualcosa di Budapest.`,
rachel:`Rachel Kovacs, storica d'archivio, dice di aver parlato con Thomas alle 19:15. Alla domanda su Budapest risponde: “Il 1984 non è una storia che Thomas avrebbe dovuto riaprire.”`,
station:`Il deposito di King's Cross è stato ritirato alle 21:07 usando un codice, senza documento. Il codice era associato a una prenotazione effettuata da Thomas due giorni prima.`,
lab:`Il referto tossicologico indica una sostanza cardiotossica assunta per via orale. L'assunzione è compatibile con una bevanda consumata poco prima del decesso. Non risultano ferite che spieghino la morte.`,
archive:`L'archivio della conferenza del 14/10/1984 mostra Thomas Vale, Edward Hart e una terza persona indicata solo come R.K. Margaret non compare nell'elenco. La conferenza fu seguita da un accordo privato mai pubblicato.`
},
helps:{1:`Livello 1 — Direzione: non avete un solo mistero. Ci sono la morte, gli spostamenti della sera e la data del 1984. Cercate i collegamenti fra queste tre cose.`,2:`Livello 2 — Dettaglio: una bevanda, un messaggio e un deposito bagagli possono essere letti insieme. E la data 14/10/1984 compare in più di un luogo.`,3:`Livello 3 — Svolta: provate a ricostruire chi poteva sapere del passato di Thomas, chi poteva raggiungerlo quella sera e quale oggetto è stato preparato prima della sua morte.`},
solution:`La soluzione completa è: Rachel Kovacs ha ucciso Thomas Vale somministrandogli una sostanza cardiotossica nella bevanda. Il movente nasce dall'accordo segreto del 14/10/1984 all'Hotel Gellért: Thomas e Edward avevano sottratto e poi nascosto una copia di documenti che riguardavano Rachel e la sua famiglia. Thomas aveva conservato l'originale come leva. Nel 2026 Rachel ha scoperto che Thomas voleva riaprire la vicenda e recuperare il deposito di King's Cross. Ha usato il loro incontro delle 19:15 per predisporre la bevanda e ha cercato di recuperare il materiale attraverso il codice del deposito. La lettera serve a far capire che la vecchia promessa è tornata a galla. Margaret ed Edward hanno entrambi motivi per sembrare sospetti, ma i loro alibi e gli altri indizi li collocano in piste differenti.`
};
function load(){try{return Object.assign(clone(initial),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return clone(initial)}}function save(s){localStorage.setItem(KEY,JSON.stringify(s))}function has(s,c){return s.clues.includes(c)}function add(s,c){if(!has(s,c))s.clues.push(c)}function log(s,q,a){s.history.push({q,a});s.turn++;save(s);return a}function any(q,words){return words.some(w=>q.includes(w))}
function final(s,q){const ready=['scene','letter','tea','receipt','phone','book','notebook','rachel','station','lab','archive'].every(c=>has(s,c));if(!ready)return `Il Master non conferma ancora la soluzione. Per arrivare alla fase finale dovete collegare la scena, la causa della morte, il 14/10/1984, gli spostamenti e almeno un interrogatorio.`;const rachel=any(q,['rachel','kovacs']);const poison=any(q,['veleno','sostanza','tossic','bevanda','te']);const bud=any(q,['budapest','1984','gellert','gellért']);if(rachel&&poison&&bud){s.finished=true;save(s);return C.solution+`\n\n— VERIFICA FINALE COMPLETATA —\nAvete ricostruito i cinque elementi richiesti: chi, come, perché, cosa accadde a Budapest e perché il passato è riemerso ora.`}return `Potete tentare l'accusa, ma deve spiegare insieme CHI, COME, PERCHÉ, COSA ACCADDE A BUDAPEST NEL 1984 e PERCHÉ È RIEMERSO ORA.`}
function parse(s,input){const q=norm(input);if(!q)return 'Dite cosa volete fare.';if(any(q,['ricomincia','nuova partita','reset'])){const n=clone(initial);save(n);return C.opening}if(any(q,['aiuto livello 1','aiuto 1','aiuto primo']))return log(s,input,C.helps[1]);if(any(q,['aiuto livello 2','aiuto 2','aiuto secondo']))return log(s,input,C.helps[2]);if(any(q,['aiuto livello 3','aiuto 3','aiuto terzo']))return log(s,input,C.helps[3]);if(any(q,['soluzione','accuso','accusa','chi ha ucciso','assassino']))return log(s,input,final(s,q));
if(any(q,['scena','appartamento','corpo','tazza','cucchiaino'])){add(s,'scene');if(any(q,['tazza','cucchiaino','bevanda']))add(s,'tea');return log(s,input,C.clues.scene+(has(s,'tea')?'\n\n'+C.clues.tea:''))}
if(any(q,['busta','lettera','foglio','frase'])){add(s,'letter');return log(s,input,C.clues.letter)}
if(any(q,['scrivania','ricevuta','cestino'])){add(s,'receipt');return log(s,input,C.clues.receipt)}
if(any(q,['telefono','messaggio','chiamata','numero'])){add(s,'phone');return log(s,input,C.clues.phone)}
if(any(q,['libreria','libro','budapest','ungheria','gellert','1984'])){add(s,'book');return log(s,input,C.clues.book)}
if(any(q,['taccuino','appunti','iniziali','promessa','copia','originale'])){add(s,'notebook');return log(s,input,C.clues.notebook)}
if(any(q,['margaret','ex moglie'])){add(s,'margaret');return log(s,input,C.clues.margaret)}
if(any(q,['edward','hart','socio'])){add(s,'edward');return log(s,input,C.clues.edward)}
if(any(q,['rachel','kovacs','storica','archivista'])){add(s,'rachel');return log(s,input,C.clues.rachel)}
if(any(q,['stazione','king cross','deposito','bagagli','codice'])){add(s,'station');return log(s,input,C.clues.station)}
if(any(q,['laboratorio','tossicologia','referto','veleno','sostanza','autopsia'])){add(s,'lab');return log(s,input,C.clues.lab)}
if(any(q,['archivio','conferenza','elenco','accordo'])){add(s,'archive');return log(s,input,C.clues.archive)}
if(any(q,['orario','cronologia','confront','tempo','ore'])){let a=[];if(has(s,'margaret'))a.push('20:10–20:35 — incontro con Margaret.');if(has(s,'receipt'))a.push('18:32 — deposito a King’s Cross.');if(has(s,'station'))a.push('21:07 — ritiro del deposito.');if(has(s,'rachel'))a.push('19:15 — incontro con Rachel.');if(has(s,'phone'))a.push('21:41 — messaggio; 21:53 — chiamata persa.');return log(s,input,a.length?a.join('\n'):'Avete ancora pochi orari: cercate documenti e interrogatori.')}
if(any(q,['sospettati','chi sono','indagati']))return log(s,input,'I nomi emersi sono Margaret Vale, Edward Hart e Rachel Kovacs. Il fascicolo non assegna loro un ruolo: dovrete verificarlo voi.');if(any(q,['teoria','penso','credo','sospetto','forse']))return log(s,input,'Teoria registrata. Il Master non la corregge: cercate una prova indipendente che la sostenga o la smentisca.');return log(s,input,'Azione non ancora associata a un elemento preciso. Provate a specificare un luogo, un oggetto, una persona, un documento o una domanda.');}
window.UltimaLetteraEngine={load,save,parse,caseData:C,reset:function(){const n=clone(initial);save(n);return n},clueCount:s=>s.clues.length};})();