/* 1 KM E SI MANGIA — PARCHEGGI MEZZI PESANTI */
(function(){
  'use strict';
  const OVERPASS=[
    'https://overpass-api.de/api/interpreter',
    'https://overpass.kumi.systems/api/interpreter',
    'https://overpass.private.coffee/api/interpreter'
  ];
  const SEARCH_RADIUS=20000;
  const EXIT_RADIUS=12000;
  const state={pos:null,exits:[],results:[],map:null,markers:null};
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function dist(a,b){const R=6371000,rad=Math.PI/180,dLat=(b.lat-a.lat)*rad,dLon=(b.lon-a.lon)*rad,la=a.lat*rad,lb=b.lat*rad;const x=Math.sin(dLat/2)**2+Math.cos(la)*Math.cos(lb)*Math.sin(dLon/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
  function fmt(m){return m<1000?Math.round(m)+' m':(m/1000).toFixed(1).replace('.',',')+' km';}
  function coord(e){if(typeof e.lat==='number'&&typeof e.lon==='number')return {lat:e.lat,lon:e.lon};if(e.center&&typeof e.center.lat==='number'&&typeof e.center.lon==='number')return {lat:e.center.lat,lon:e.center.lon};return null;}
  function queryFor(pos,radius){
    const lat=pos.lat,lon=pos.lon;
    return `[out:json][timeout:35];(nwr["amenity"="parking"](around:${radius},${lat},${lon});nwr["amenity"="parking"]["hgv"](around:${radius},${lat},${lon});nwr["amenity"="parking"]["access:hgv"](around:${radius},${lat},${lon});nwr["amenity"="parking"]["goods"](around:${radius},${lat},${lon});nwr["highway"="services"](around:${radius},${lat},${lon}););out center tags;`;
  }
  async function overpass(q){let last=null;for(const url of OVERPASS){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),40000);const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','User-Agent':'1KMESIMANGIA/1.0'},body:'data='+encodeURIComponent(q),signal:c.signal});clearTimeout(t);if(!r.ok)throw new Error('HTTP '+r.status);return await r.json();}catch(e){last=e;}}throw last||new Error('Servizio mappe non disponibile');}
  async function loadExits(){try{const r=await fetch('uscite.json',{cache:'no-store'});const d=await r.json();state.exits=Array.isArray(d)?d.filter(x=>Number.isFinite(Number(x.lat))&&Number.isFinite(Number(x.lon))):[];}catch(e){state.exits=[];}}
  function nearestExit(p){let best=null,bestD=Infinity;for(const e of state.exits){const d=dist(p,{lat:Number(e.lat),lon:Number(e.lon)});if(d<bestD){bestD=d;best=e;}}return best?{data:best,distance:bestD}:null;}
  function tagBool(v){return ['yes','designated','permissive','true','1'].includes(String(v||'').toLowerCase());}
  function parkingName(tags){return tags.name||tags.operator||((tags.highway==='services')?'Area di servizio':'Parcheggio mezzi pesanti');}
  function services(tags){const out=[];if(tagBool(tags.toilets))out.push('WC');if(tagBool(tags.shower))out.push('Doccia');if(tagBool(tags.lit))out.push('Illuminato');if(tagBool(tags.surveillance))out.push('Videosorveglianza');if(tags.fee==='yes')out.push('A pagamento');if(tags.capacity_hgv||tags['capacity:hgv'])out.push('Posti TIR: '+(tags.capacity_hgv||tags['capacity:hgv']));return out;}
  function limits(tags){return {maxheight:tags.maxheight||tags['maxheight:physical']||null,maxwidth:tags.maxwidth||null,maxlength:tags.maxlength||null,maxweight:tags.maxweight||null};}
  function normalize(e){const tags=e.tags||{},p=coord(e);if(!p)return null;const ex=nearestExit(p),lim=limits(tags);const compat=window.verificaCompatibilitaParcheggio?window.verificaCompatibilitaParcheggio(Object.assign({},lim,{maxheight:lim.maxheight,maxwidth:lim.maxwidth,maxlength:lim.maxlength,maxweight:lim.maxweight})):null;return {id:e.type+'-'+e.id,lat:p.lat,lon:p.lon,tags,name:parkingName(tags),distance:state.pos?dist(state.pos,p):Infinity,exit:ex,limits:lim,compat,services:services(tags),truckExplicit:tagBool(tags.hgv)||tagBool(tags['access:hgv'])||tagBool(tags.goods)||tags.highway==='services'};}
  function isUseful(x){return x&&x.truckExplicit;}
  function renderMap(){if(!state.map||!window.L)return;state.map.invalidateSize();if(state.markers)state.markers.clearLayers();else state.markers=L.layerGroup().addTo(state.map);const pts=[];if(state.pos){const m=L.marker([state.pos.lat,state.pos.lon]);m.bindPopup('<b>La tua posizione</b>');state.markers.addLayer(m);pts.push([state.pos.lat,state.pos.lon]);}for(const r of state.results){const color=r.compat&&r.compat.ok===true?'#176534':r.compat&&r.compat.ok===false?'#9a2929':'#8a5a00';const icon=L.divIcon({className:'',html:`<div style="width:28px;height:28px;border-radius:50% 50% 50% 0;transform:rotate(-45deg);background:${color};border:3px solid #fff;box-shadow:0 2px 8px rgba(0,0,0,.3)"><div style="transform:rotate(45deg);color:#fff;text-align:center;font-weight:800;font-size:14px;line-height:23px">🚛</div></div>`,iconSize:[34,34],iconAnchor:[17,30]});const m=L.marker([r.lat,r.lon],{icon});m.bindPopup(`<b>${esc(r.name)}</b><br>${r.distance!==Infinity?fmt(r.distance):''}<br>${r.exit?`Uscita ${esc(r.exit.data.nome||'')} · ${fmt(r.exit.distance)}`:''}`);state.markers.addLayer(m);pts.push([r.lat,r.lon]);}if(pts.length===1)state.map.setView(pts[0],12);else if(pts.length>1)state.map.fitBounds(pts,{padding:[30,30]});}
  function card(r,i){const c=r.compat;const chip=c&&c.ok===true?'<span class="mp-chip good">🟢 Compatibile</span>':c&&c.ok===false?'<span class="mp-chip bad">🔴 Non compatibile</span>':'<span class="mp-chip warn">🟡 Da verificare</span>';const lim=[];if(r.limits.maxheight)lim.push('H max '+esc(r.limits.maxheight)+' m');if(r.limits.maxwidth)lim.push('Larg. max '+esc(r.limits.maxwidth)+' m');if(r.limits.maxlength)lim.push('Lung. max '+esc(r.limits.maxlength)+' m');if(r.limits.maxweight)lim.push('Peso max '+esc(r.limits.maxweight));const serv=r.services.length?r.services.join(' · '):'Servizi non indicati';return `<article class="mp-card"><h3>${esc(r.name)}</h3><div class="mp-meta"><span class="mp-chip">📍 ${fmt(r.distance)}</span>${r.exit?`<span class="mp-chip">🛣️ ${fmt(r.exit.distance)} dall'uscita ${esc(r.exit.data.nome||'')}</span>`:''}${chip}</div><div class="mp-services">${esc(serv)}${lim.length?'<br><strong>Limiti dichiarati:</strong> '+lim.join(' · '):'<br><span>Limiti dimensionali non pubblicati.</span>'}</div><div class="mp-card-actions"><button class="mp-btn dark" type="button" data-nav-index="${i}">🧭 NAVIGA</button><button class="mp-btn" type="button" data-map-index="${i}">📍 MAPPA</button></div></article>`;}
  function renderList(){const list=$('mpList');if(!state.results.length){list.innerHTML='<div class="mp-empty">Nessun parcheggio per mezzi pesanti trovato nell’area cercata. Prova ad aggiornare la posizione o a spostarti più vicino all’autostrada.</div>';return;}list.innerHTML=state.results.map(card).join('');list.querySelectorAll('[data-nav-index]').forEach(b=>b.onclick=()=>{const r=state.results[Number(b.dataset.navIndex)];if(window.apriNavigazione)window.apriNavigazione({nome:r.name,lat:r.lat,lon:r.lon});else window.open(`https://www.google.com/maps/dir/?api=1&destination=${r.lat},${r.lon}&travelmode=driving`,'_blank');});list.querySelectorAll('[data-map-index]').forEach(b=>b.onclick=()=>{const r=state.results[Number(b.dataset.mapIndex)];state.map.setView([r.lat,r.lon],16);state.markers.eachLayer(m=>{if(m.getLatLng&&Math.abs(m.getLatLng().lat-r.lat)<1e-7&&Math.abs(m.getLatLng().lng-r.lon)<1e-7)m.openPopup();});});}
  async function search(pos,mode){state.pos=pos;$('mpStatus').textContent='Cerco parcheggi…';$('mpList').innerHTML='<div class="mp-loading">⏳ Ricerca dei parcheggi per mezzi pesanti in corso…</div>';try{const data=await overpass(queryFor(pos,mode==='exit'?EXIT_RADIUS:SEARCH_RADIUS));const arr=(data.elements||[]).map(normalize).filter(isUseful);const seen=new Set();state.results=arr.filter(x=>{if(seen.has(x.id))return false;seen.add(x.id);return true;}).sort((a,b)=>a.distance-b.distance).slice(0,60);$('mpStatus').textContent=state.results.length+' risultati';renderList();renderMap();}catch(e){$('mpStatus').textContent='Errore ricerca';$('mpList').innerHTML='<div class="mp-empty">Non riesco a contattare il servizio dati dei parcheggi in questo momento. Riprova tra poco.</div>';}}
  function initMap(){if(!window.L)return;state.map=L.map('mpMap',{zoomControl:true}).setView([41.9,12.5],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(state.map);}
  function locate(){if(!navigator.geolocation){$('mpStatus').textContent='GPS non disponibile';return;}$('mpStatus').textContent='Acquisizione posizione…';navigator.geolocation.getCurrentPosition(p=>search({lat:p.coords.latitude,lon:p.coords.longitude},'near'),()=>{$('mpStatus').textContent='Posizione non disponibile';}, {enableHighAccuracy:true,timeout:12000,maximumAge:60000});}
  function nearestExitSearch(){if(!state.pos){locate();return;}search(state.pos,'exit');}
  function loadProfile(){const v=window.getProfiloMezzoPesante?window.getProfiloMezzoPesante():window._defaultMezzoPesante;['Tipo','L','W','H','P','R'];$('mpTipo').value=v.tipo;$('mpL').value=v.lunghezza;$('mpW').value=v.larghezza;$('mpH').value=v.altezza;$('mpP').value=v.peso;$('mpR').checked=!!v.rimorchio;}
  function saveProfile(){const v={tipo:$('mpTipo').value,lunghezza:Number($('mpL').value)||0,larghezza:Number($('mpW').value)||0,altezza:Number($('mpH').value)||0,peso:Number($('mpP').value)||0,rimorchio:$('mpR').checked};if(window.salvaProfiloMezzoPesante)window.salvaProfiloMezzoPesante(v);$('mpSaved').textContent='✓ Dati del mezzo salvati su questo dispositivo';if(state.results.length){state.results=state.results.map(r=>Object.assign(r,{compat:window.verificaCompatibilitaParcheggio(r.limits)}));renderList();renderMap();}}
  document.addEventListener('DOMContentLoaded',async()=>{initMap();loadProfile();await loadExits();$('mpLocate').onclick=locate;$('mpNearestExit').onclick=nearestExitSearch;$('mpRefresh').onclick=()=>state.pos?search(state.pos,'near'):locate();$('mpSave').onclick=saveProfile;});
})();
